/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2026-08-20 23:59:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.campus.dao.*;
import com.campus.model.*;
import com.campus.util.SessionUtil;
import java.util.*;
import com.campus.model.User;
import com.campus.util.SessionUtil;

public final class my_002dgoods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/client/../common/header.jsp", Long.valueOf(1784123205161L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("com.campus.dao");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("com.campus.model");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.campus.util.SessionUtil");
    _jspx_imports_classes.add("com.campus.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User u = SessionUtil.getUser(request);
    List<Goods> list = new GoodsDao().listBySeller(u.getUserId());

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>我的发布 - 校园二手交易平台</title></head>\n");
      out.write("<body>\n");
      out.write('\n');
      out.write('\n');

    User loginUser = SessionUtil.getUser(request);
    String ctx = request.getContextPath();
    boolean isAdmin = loginUser != null && loginUser.getRole() == 1;

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(ctx);
      out.write("/assets/style.css\">\n");
      out.write("<header class=\"navbar\">\n");
      out.write("    <div class=\"logo\">\n");
      out.write("        <i class=\"fas fa-store-alt\"></i>\n");
      out.write("        <span>校园二手交易平台</span>\n");
      out.write("    </div>\n");
      out.write("    <nav class=\"nav-links\">\n");
      out.write("        ");
 if (loginUser != null && !isAdmin) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/home.jsp\"><i class=\"fas fa-home\"></i><span>首页</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/activities.jsp\"><i class=\"fas fa-calendar-alt\"></i><span>活动</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/cart.jsp\"><i class=\"fas fa-shopping-cart\"></i><span>购物车</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/orders.jsp\"><i class=\"fas fa-clipboard-list\"></i><span>买入</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/seller-orders.jsp\"><i class=\"fas fa-handshake\"></i><span>卖出</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/profile.jsp\"><i class=\"fas fa-user-circle\"></i><span>我的</span></a>\n");
      out.write("            <span class=\"points-badge\"><i class=\"fas fa-coins\"></i> ");
      out.print(loginUser.getPointsBalance());
      out.write("</span>\n");
      out.write("        ");
 } else if (isAdmin) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/index.jsp\"><i class=\"fas fa-tachometer-alt\"></i><span>仪表盘</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/goods.jsp\"><i class=\"fas fa-box\"></i><span>商品</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/activities.jsp\"><i class=\"fas fa-star\"></i><span>活动</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/users.jsp\"><i class=\"fas fa-users\"></i><span>用户</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/orders.jsp\"><i class=\"fas fa-shopping-bag\"></i><span>订单</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/points.jsp\"><i class=\"fas fa-chart-line\"></i><span>积分</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/config.jsp\"><i class=\"fas fa-cog\"></i><span>配置</span></a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (loginUser != null) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/action/logout\"><i class=\"fas fa-sign-out-alt\"></i><span>退出</span></a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");
      out.write("    ");
 if (request.getParameter("msg") != null) { 
      out.write("<div class=\"alert alert-success\"><i class=\"fas fa-check-circle\"></i> ");
      out.print(request.getParameter("msg"));
      out.write("</div>");
 } 
      out.write("\n");
      out.write("    <div class=\"flex-between mb16\">\n");
      out.write("        <div class=\"card-title\" style=\"margin:0;border:0;padding:0\"><i class=\"fas fa-box\" style=\"color:var(--primary)\"></i> 我的发布</div>\n");
      out.write("        <a class=\"btn btn-primary btn-sm\" href=\"publish.jsp\"><i class=\"fas fa-plus\"></i> 发布</a>\n");
      out.write("    </div>\n");
      out.write("    ");
 for (Goods g : list) { 
      out.write("\n");
      out.write("    <div class=\"card flex-between\">\n");
      out.write("        <div class=\"flex\">\n");
      out.write("            <img src=\"");
      out.print(com.campus.util.ImageUtil.getImageUrl(request, g.getCover()));
      out.write("\" style=\"width:60px;height:60px;object-fit:cover;border-radius:var(--radius-btn)\" onerror=\"this.onerror=null;this.src='");
      out.print(request.getContextPath());
      out.write("/assets/placeholder.svg'\">\n");
      out.write("            <div>\n");
      out.write("                <div style=\"font-weight:600\"><i class=\"fas fa-box\" style=\"color:var(--primary-light)\"></i> ");
      out.print(g.getTitle());
      out.write("</div>\n");
      out.write("                <div class=\"price mt8\"><i class=\"fas fa-coins\"></i> ");
      out.print(g.getPricePoints());
      out.write(" 积分</div>\n");
      out.write("                <span class=\"tag tag-info mt8\"><i class=\"fas fa-info-circle\"></i> ");
      out.print(g.getStatusText());
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("            ");
 if (g.getStatus() == 1) { 
      out.write("\n");
      out.write("            <a class=\"btn btn-warning btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/action/offShelf?id=");
      out.print(g.getGoodsId());
      out.write("\"><i class=\"fas fa-arrow-down\"></i> 下架</a>\n");
      out.write("            ");
 } else if (g.getStatus() == 2) { 
      out.write("\n");
      out.write("            <a class=\"btn btn-success btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/action/onShelf?id=");
      out.print(g.getGoodsId());
      out.write("\"><i class=\"fas fa-arrow-up\"></i> 上架</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
