/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2026-08-20 23:59:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.campus.dao.*;
import com.campus.model.*;
import com.campus.util.SessionUtil;
import java.util.*;
import com.campus.model.User;
import com.campus.util.SessionUtil;

public final class publish_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/client/../common/header.jsp", Long.valueOf(1784123205161L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("com.campus.dao");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("com.campus.model");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.campus.util.SessionUtil");
    _jspx_imports_classes.add("com.campus.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User u = SessionUtil.getUser(request);
    List<Goods> myGoods = new GoodsDao().listBySeller(u.getUserId());
    List<String[]> cats = new GoodsDao().categories();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>发布闲置 - 校园二手交易平台</title></head>\n");
      out.write("<body>\n");
      out.write('\n');
      out.write('\n');

    User loginUser = SessionUtil.getUser(request);
    String ctx = request.getContextPath();
    boolean isAdmin = loginUser != null && loginUser.getRole() == 1;

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(ctx);
      out.write("/assets/style.css\">\n");
      out.write("<header class=\"navbar\">\n");
      out.write("    <div class=\"logo\">\n");
      out.write("        <i class=\"fas fa-store-alt\"></i>\n");
      out.write("        <span>校园二手交易平台</span>\n");
      out.write("    </div>\n");
      out.write("    <nav class=\"nav-links\">\n");
      out.write("        ");
 if (loginUser != null && !isAdmin) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/home.jsp\"><i class=\"fas fa-home\"></i><span>首页</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/activities.jsp\"><i class=\"fas fa-calendar-alt\"></i><span>活动</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/cart.jsp\"><i class=\"fas fa-shopping-cart\"></i><span>购物车</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/orders.jsp\"><i class=\"fas fa-clipboard-list\"></i><span>买入</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/seller-orders.jsp\"><i class=\"fas fa-handshake\"></i><span>卖出</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/client/profile.jsp\"><i class=\"fas fa-user-circle\"></i><span>我的</span></a>\n");
      out.write("            <span class=\"points-badge\"><i class=\"fas fa-coins\"></i> ");
      out.print(loginUser.getPointsBalance());
      out.write("</span>\n");
      out.write("        ");
 } else if (isAdmin) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/index.jsp\"><i class=\"fas fa-tachometer-alt\"></i><span>仪表盘</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/goods.jsp\"><i class=\"fas fa-box\"></i><span>商品</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/activities.jsp\"><i class=\"fas fa-star\"></i><span>活动</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/users.jsp\"><i class=\"fas fa-users\"></i><span>用户</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/orders.jsp\"><i class=\"fas fa-shopping-bag\"></i><span>订单</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/points.jsp\"><i class=\"fas fa-chart-line\"></i><span>积分</span></a>\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/admin/config.jsp\"><i class=\"fas fa-cog\"></i><span>配置</span></a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (loginUser != null) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print(ctx);
      out.write("/action/logout\"><i class=\"fas fa-sign-out-alt\"></i><span>退出</span></a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </nav>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");
      out.write("    ");
 if (request.getParameter("err") != null) { 
      out.write("<div class=\"alert alert-error\"><i class=\"fas fa-exclamation-circle\"></i> ");
      out.print(request.getParameter("err"));
      out.write("</div>");
 } 
      out.write("\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div class=\"card-title\"><i class=\"fas fa-plus-circle\" style=\"color:var(--primary)\"></i> 发布闲置</div>\n");
      out.write("        ");
 if (u.getVerifyStatus() != 2) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-error\"><i class=\"fas fa-exclamation-circle\"></i> 未认证用户不能发布，请先<a href=\"profile.jsp\">提交认证</a></div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <form action=\"");
      out.print(request.getContextPath());
      out.write("/action/publish\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-heading\"></i> 标题（20字内）</label><input class=\"input\" name=\"title\" maxlength=\"20\" placeholder=\"请输入商品标题\" required></div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-align-left\"></i> 描述</label><textarea class=\"input\" name=\"description\" rows=\"4\" maxlength=\"200\" placeholder=\"详细描述商品状况\" required></textarea></div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-tag\"></i> 分类</label>\n");
      out.write("                <select class=\"select\" name=\"categoryId\" required>\n");
      out.write("                    ");
 for (String[] c : cats) { 
      out.write("<option value=\"");
      out.print(c[0]);
      out.write('"');
      out.write('>');
      out.print(c[1]);
      out.write("</option>");
 } 
      out.write("\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-coins\"></i> 积分价格</label><input class=\"input\" name=\"pricePoints\" type=\"number\" min=\"1\" placeholder=\"请输入积分价格\" required></div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-star\"></i> 新旧程度</label>\n");
      out.write("                <select class=\"select\" name=\"conditionLevel\">\n");
      out.write("                    <option value=\"0\">全新</option><option value=\"1\">几乎全新</option><option value=\"2\">轻微使用</option><option value=\"3\">明显磨损</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-image\"></i> 上传封面图</label><input class=\"input\" name=\"imageFile\" type=\"file\" accept=\"image/*\"></div>\n");
      out.write("            <div class=\"form-item\"><label><i class=\"fas fa-link\"></i> 或填写图片链接</label><input class=\"input\" name=\"imageUrl\" placeholder=\"https://example.com/photo.jpg\"></div>\n");
      out.write("            <button class=\"btn btn-primary\"><i class=\"fas fa-paper-plane\"></i> 提交审核</button>\n");
      out.write("        </form>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
