/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2026-08-20 23:59:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.campus.dao.*;
import com.campus.model.*;
import java.util.*;
import com.campus.dao.ActivityDao;

public final class points_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/admin/../common/admin-head.jsp", Long.valueOf(1784123205151L));
    _jspx_dependants.put("/admin/../common/admin-sidebar.jsp", Long.valueOf(1784123205156L));
    _jspx_dependants.put("/admin/../common/admin-foot.jsp", Long.valueOf(1784123205146L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("com.campus.dao");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("com.campus.model");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.campus.dao.ActivityDao");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 pageContext.setAttribute("adminTitle", "积分审计"); 
      out.write('\n');
 List<PointsLog> logs = new PointsDao().listAll(); 
      out.write('\n');
      out.write('\n');

    String ctx = request.getContextPath();
    String uri = request.getRequestURI();
    String title = (String) pageContext.getAttribute("adminTitle");
    if (title == null) title = "管理后台";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>");
      out.print(title);
      out.write(" - 校园二手管理</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(ctx);
      out.write("/assets/style.css\">\n");
      out.write("</head>\n");
      out.write("<body class=\"admin-body\">\n");
      out.write("<div class=\"admin-layout\">\n");
      out.write('\n');
      out.write('\n');
 int pendingCount = 0; try { pendingCount = new ActivityDao().listPending().size(); } catch (Exception ignored) {} 
      out.write("\n");
      out.write("<aside class=\"admin-sidebar\">\n");
      out.write("    <div class=\"admin-brand\"><i class=\"fas fa-store-alt\"></i> <em>校园二手</em> 管理</div>\n");
      out.write("    <nav class=\"admin-menu\">\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/index.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/index.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("            <span>仪表盘</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/goods.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/goods.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-box\"></i>\n");
      out.write("            <span>商品管理</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/activities.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/activities.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-star\"></i>\n");
      out.write("            <span>活动管理</span>\n");
      out.write("            ");
 if (pendingCount > 0) { 
      out.write("<span class=\"badge\" style=\"background:var(--color-danger);color:#fff;font-size:11px;padding:1px 7px;border-radius:10px;margin-left:4px\">");
      out.print(pendingCount);
      out.write("</span>");
 } 
      out.write("\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/users.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/users.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-users\"></i>\n");
      out.write("            <span>用户管理</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/orders.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/orders.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-shopping-bag\"></i>\n");
      out.write("            <span>订单管理</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/points.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/points.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-chart-line\"></i>\n");
      out.write("            <span>积分审计</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/admin/config.jsp\" class=\"admin-menu-item ");
      out.print(uri.contains("/admin/config.jsp")?"active":"");
      out.write("\">\n");
      out.write("            <i class=\"fas fa-cog\"></i>\n");
      out.write("            <span>系统配置</span>\n");
      out.write("        </a>\n");
      out.write("    </nav>\n");
      out.write("    <div class=\"admin-sidebar-foot\">\n");
      out.write("        <a href=\"");
      out.print(ctx);
      out.write("/client/home.jsp\"><i class=\"fas fa-arrow-left\"></i> 返回前台</a>\n");
      out.write("    </div>\n");
      out.write("</aside>\n");
      out.write("\n");
      out.write("<main class=\"admin-main\">\n");
      out.write("<div class=\"admin-topbar\">\n");
      out.write("    <i class=\"fas fa-user-shield\"></i> 管理员\n");
      out.write("    <a href=\"");
      out.print(ctx);
      out.write("/action/logout\"><i class=\"fas fa-sign-out-alt\"></i> 退出</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"admin-page-title\"><i class=\"fas fa-chart-line\" style=\"color:var(--primary)\"></i> 积分审计</div>\n");
      out.write("<table class=\"table card\">\n");
      out.write("    <tr><th><i class=\"fas fa-clock\"></i> 时间</th><th><i class=\"fas fa-user\"></i> 用户ID</th><th><i class=\"fas fa-exchange-alt\"></i> 类型</th><th><i class=\"fas fa-tag\"></i> 来源</th><th><i class=\"fas fa-coins\"></i> 数量</th><th><i class=\"fas fa-wallet\"></i> 余额</th><th><i class=\"fas fa-comment\"></i> 描述</th></tr>\n");
      out.write("    ");
 for (PointsLog p : logs) { 
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td><i class=\"fas fa-clock\" style=\"color:var(--text-secondary)\"></i> ");
      out.print(p.getCreateTime());
      out.write("</td>\n");
      out.write("        <td><i class=\"fas fa-user\" style=\"color:var(--text-secondary)\"></i> ");
      out.print(p.getUserId());
      out.write("</td>\n");
      out.write("        <td>");
 if(p.getType()==1){ 
      out.write("<span class=\"tag tag-success\"><i class=\"fas fa-arrow-down\"></i> 收入</span>");
 }else{ 
      out.write("<span class=\"tag tag-danger\"><i class=\"fas fa-arrow-up\"></i> 支出</span>");
 } 
      out.write("</td>\n");
      out.write("        <td><i class=\"fas fa-tag\" style=\"color:var(--text-secondary)\"></i> ");
      out.print(p.getSourceText());
      out.write("</td>\n");
      out.write("        <td style=\"color:");
      out.print(p.getType()==1?"var(--color-success)":"var(--color-danger)");
      out.write(";font-weight:700\">");
      out.print(p.getType()==1?"+":"-");
      out.print(p.getAmount());
      out.write("</td>\n");
      out.write("        <td><i class=\"fas fa-wallet\" style=\"color:var(--text-secondary)\"></i> ");
      out.print(p.getBalanceAfter());
      out.write("</td>\n");
      out.write("        <td><i class=\"fas fa-comment\" style=\"color:var(--text-secondary)\"></i> ");
      out.print(p.getDescription());
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("</main>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
