/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2026-08-08 05:14:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>登录 - 校园二手交易平台</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body{\n");
      out.write("            background:linear-gradient(135deg,var(--primary-dark),var(--primary));\n");
      out.write("            min-height:100vh;\n");
      out.write("            display:flex;\n");
      out.write("            align-items:center;\n");
      out.write("            justify-content:center;\n");
      out.write("        }\n");
      out.write("        .login-card{\n");
      out.write("            background:#fff;\n");
      out.write("            border-radius:20px;\n");
      out.write("            box-shadow:0 20px 60px rgba(0,0,0,0.15);\n");
      out.write("            padding:40px 36px;\n");
      out.write("            width:100%;\n");
      out.write("            max-width:400px;\n");
      out.write("        }\n");
      out.write("        .login-card .login-logo{\n");
      out.write("            text-align:center;\n");
      out.write("            margin-bottom:28px;\n");
      out.write("        }\n");
      out.write("        .login-card .login-logo i{\n");
      out.write("            font-size:48px;\n");
      out.write("            color:var(--primary);\n");
      out.write("            margin-bottom:12px;\n");
      out.write("            display:block;\n");
      out.write("        }\n");
      out.write("        .login-card .login-logo h2{\n");
      out.write("            font-size:22px;\n");
      out.write("            font-weight:700;\n");
      out.write("            color:var(--text-main);\n");
      out.write("        }\n");
      out.write("        .login-card .login-logo p{\n");
      out.write("            color:var(--text-secondary);\n");
      out.write("            font-size:13px;\n");
      out.write("            margin-top:6px;\n");
      out.write("        }\n");
      out.write("        .login-card .btn-primary{\n");
      out.write("            width:100%;\n");
      out.write("            padding:12px;\n");
      out.write("            font-size:16px;\n");
      out.write("            justify-content:center;\n");
      out.write("        }\n");
      out.write("        .login-hint{\n");
      out.write("            margin-top:20px;\n");
      out.write("            padding:12px 16px;\n");
      out.write("            background:var(--primary-lighter);\n");
      out.write("            border-radius:var(--radius-btn);\n");
      out.write("            font-size:12px;\n");
      out.write("            color:var(--text-secondary);\n");
      out.write("            text-align:center;\n");
      out.write("        }\n");
      out.write("        .login-hint strong{color:var(--primary)}\n");
      out.write("        .captcha-row{\n");
      out.write("            display:flex;\n");
      out.write("            gap:10px;\n");
      out.write("            align-items:center;\n");
      out.write("        }\n");
      out.write("        .captcha-row .input{\n");
      out.write("            flex:1;\n");
      out.write("            margin:0;\n");
      out.write("            text-transform:uppercase;\n");
      out.write("        }\n");
      out.write("        .captcha-row img{\n");
      out.write("            height:40px;\n");
      out.write("            border-radius:var(--radius-btn);\n");
      out.write("            cursor:pointer;\n");
      out.write("            border:1px solid var(--border-color);\n");
      out.write("        }\n");
      out.write("        .captcha-row .captcha-refresh{\n");
      out.write("            color:var(--text-secondary);\n");
      out.write("            font-size:13px;\n");
      out.write("            white-space:nowrap;\n");
      out.write("            cursor:pointer;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"login-card\">\n");
      out.write("    <div class=\"login-logo\">\n");
      out.write("        <i class=\"fas fa-store-alt\"></i>\n");
      out.write("        <h2>校园二手交易平台</h2>\n");
      out.write("        <p>登录后开启校园二手之旅</p>\n");
      out.write("    </div>\n");
      out.write("    ");
 if (request.getParameter("err") != null) { 
      out.write("\n");
      out.write("    <div class=\"alert alert-error\"><i class=\"fas fa-exclamation-circle\"></i> ");
      out.print(request.getParameter("err"));
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/action/login\" method=\"post\">\n");
      out.write("        <div class=\"form-item\">\n");
      out.write("            <label><i class=\"fas fa-phone\"></i> 账号（手机号）</label>\n");
      out.write("            <input class=\"input\" name=\"phone\" placeholder=\"请输入手机号\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-item\">\n");
      out.write("            <label><i class=\"fas fa-lock\"></i> 密码</label>\n");
      out.write("            <input class=\"input\" name=\"password\" type=\"password\" placeholder=\"请输入密码\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-item\">\n");
      out.write("            <label><i class=\"fas fa-shield-alt\"></i> 验证码</label>\n");
      out.write("            <div class=\"captcha-row\">\n");
      out.write("                <input class=\"input\" name=\"captcha\" placeholder=\"输入验证码\" maxlength=\"4\" required>\n");
      out.write("                <img id=\"captchaImg\" src=\"");
      out.print(request.getContextPath());
      out.write("/captcha\" onclick=\"this.src='");
      out.print(request.getContextPath());
      out.write("/captcha?t='+Date.now()\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\"><i class=\"fas fa-sign-in-alt\"></i> 登录</button>\n");
      out.write("    </form>\n");
      out.write("    <div class=\"login-hint\">\n");
      out.write("        测试账号：手机 <strong>13800000000</strong> / 密码 <strong>123456</strong>（管理员）<br>\n");
      out.write("        普通用户：<strong>13800000001</strong> ~ <strong>13800000010</strong> / 密码 <strong>123456</strong>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
